<?php
/**
 * API Generation for the framework
 * 
 * PHP version 5.4
 * 
 * @category  API
 * @package   Boiler
 * @author    Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @copyright 2013 Mercian Labels
 * @license   http://www.mercianlabels.com All Rights Reserved
 * @link      http://www.mercianlabels.com
 */
namespace System\Controller\Api;


/**
 * Autogenerated class for API access to the model \Model\Task_Comment
 * 
 * PHP version 5.4
 *
 * @category API
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  All Rights Reserved
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Task_Comment extends \Controller\Api\ModelController {

	/**
	 * Parses the name of the model which this API endpoint represents to the ModelController
	 * 
	 * @return string
	 */
	protected function getModelClass() {
		return "\Model\TaskComment";
	}
}