<?php
/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace Model;

/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class EquipmentCheckout extends \System\Model\EquipmentCheckout {
	public function setAttributes($array, $set=true) {
		$u = \Core\Router::getCurrentPerson();
		if ($u !== null) {
			if (isset($array['checkout']) && $array['checkout'] > 0) {
				$array['out_actor'] = $u->id;
			}
		
			if (isset($array['checkin']) && $array['checkin'] > 0) {
				$array['in_actor'] = $u->id;
			}
		}
		return parent::setAttributes($array);
	}

	public static function Create($array) {
		$u = \Core\Router::getCurrentPerson();
		if ($u !== null) {
			$array['out_actor'] = $u->id;
			if (isset($array['checkin']) && $array['checkin'] > 0) {
				$array['in_actor'] = $u->id;
			}
		}
		return parent::Create($array);
	}
}
