<?php
/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace Model;

/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Equipment extends \System\Model\Equipment {
	function isCheckedOut() {
		$checkouts = $this->getEquipmentCheckouts();
		return count($checkouts) > 0 && $checkouts[count($checkouts)-1]->checkin == 0;
	}
	
	function isInService() {
		return $this->in_service==1;
	}
	
	function getEquipmentCheckouts() {
		return array_reverse(\System\Library\StdLib::object_order(parent::getEquipmentCheckouts(), "checkout"));
	}
	
	public function getKeyholder() {
		$checkouts = $this->getEquipmentCheckouts();
		if (count($checkouts) == 0 || $checkouts[count($checkouts)-1]->checkin > 0) {
			return null;
		}
		return $checkouts[count($checkouts)-1]->getPerson();
	}
	
	public function CheckIn() {
		if ($this->isCheckedOut()) {
			$checkouts = $this->getEquipmentCheckouts();
			$checkouts[count($checkouts)-1]->setAttribute("checkin", time());
			return true;
		}
		return false;
	}
}