<?php
/**
 * Autogenerated model for \Model\Person
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace Model;

/**
 * Autogenerated model for \Model\Person
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Task extends \System\Model\Task {
	public function __construct($Id) {
		parent::__construct($Id);
		
		if (!$this->thread) {
			$thread = \Model\Thread::Create(array("name"=>"task[{$this->id}].thread"));
			$this->setAttribute("thread", $thread->id);
		}
	}
}