<?php
/**
 * Autogenerated model for \Model\VenueCheck
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace Model;

/**
 * Autogenerated model for \Model\VenueCheck
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class VenueCheck extends \System\Model\VenueCheck {
	public static function Create($array) {
		if (($v = \Model\Venue::Fetch($array['venue'])) == null) {
			throw new \Exception("Venue has not been specified");
		}
		$u = \Core\Router::getCurrentPerson();
		if ($u !== null) {
			$array['actor'] = $u->id;
		}
		$self = parent::Create($array);
		foreach ($v->getVenueCheckSelectedQuestions() as $vcsq) {
			$vcq = $vcsq->getVenueCheckQuestion();
			\Model\VenueCheckResponse::Create(array("venue_check"=>$self->id, "venue_check_question"=>$vcq->id));
		}
		
	}
}
