<?php
/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace System\Model;
	
/**
 * Autogenerated model for \Model\Equipment
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Equipment extends \Model\DBObject {
	
	/**
	* int(11)
	* 
	* @var int $id 
	*/
	public $id;
	
	/**
	* varchar(255)
	* 
	* @var string $name 
	*/
	public $name;
	
	/**
	* int(11)
	* 
	* @var int $category 
	*/
	public $category;
	
	/**
	* int(11)
	* 
	* @var int $in_service 
	*/
	public $in_service;	
	/**
	 * Lists all the columns in the database
	 *
	 * @return array
	 */
	public static function getDBColumns() {
		return array("id","name","category","in_service");
	}
	
	/**
	 * Gets the table name (always returns "equipment")
	 * 
	 * @param boolean $read changes the table name if a database view is provided for reading, rather than a table
	 * 
	 * @return string
	 */
	public static function getTable($read=true) {
		return "equipment";
	}
	
	/**
	 * Gets the primary key
	 * 
	 * @return array
	 */
	public static function getPrimaryKey() {
		return array("id");
	}
	
	/**
	 * Gets the field the key references
	 * 
	 * @return array
	 */
	public static function getForeignKeys() {
		$keys = array();

		$std = new \stdClass();
		$std->table = "equipment_category";
		$std->field = "id";
		
		$keys[category] = $std;	
		return $keys;
	}
		
	/**
	 * Gets all EquipmentCategory associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getCategory() {
		return \Model\EquipmentCategory::Fetch($this->category);
	}			
		
	/**
	 * Gets all objects relating to EquipmentCategory
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByCategory(EquipmentCategory $class) {
		$c = get_called_class();
		return $c::getByAttribute("category", $class->id);
	}

	/**
	 * Gets all EquipmentCheckouts relating to this model by the field equipment
	 * 
	 * @return array
	 */	
	public function getEquipmentCheckouts() {
		return \Model\EquipmentCheckout::getByEquipment($this);
	}
	
	public function bubbleUpdateResult($update_result, $loop_control=array()) {
		if (in_array(get_class(), $loop_control)) {
			return;
		}
		$loop_control[] = get_class();
		$update_result->module = get_class();
		$c = get_class();
		$update_result->module_table = $c::getTable();
		if (\System\Library\StdLib::parent_method_exists($this, "bubbleUpdateResult", __CLASS__)) {
			parent::bubbleUpdateResult($update_result, $loop_control);	
		}
		\Library\RTCQueue::Send("/model/".self::getTable()."/{$this->id}", $update_result);
		return;
		$obj = $this->getCategory();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}
	}
}