<?php
/**
 * Autogenerated model for \Model\Event
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace System\Model;
	
/**
 * Autogenerated model for \Model\Event
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Event extends \Model\DBObject {
	
	/**
	* int(11)
	* 
	* @var int $id 
	*/
	public $id;
	
	/**
	* int(11)
	* 
	* @var int $start 
	*/
	public $start;
	
	/**
	* int(11)
	* 
	* @var int $end 
	*/
	public $end;
	
	/**
	* int(11)
	* 
	* @var int $venue 
	*/
	public $venue;
	
	/**
	* text
	* 
	* @var unknown_type $description 
	*/
	public $description;
	
	/**
	* int(11)
	* 
	* @var int $status 
	*/
	public $status;
	
	/**
	* int(11)
	* 
	* @var int $parent 
	*/
	public $parent;	
	/**
	 * Lists all the columns in the database
	 *
	 * @return array
	 */
	public static function getDBColumns() {
		return array("id","start","end","venue","description","status","parent");
	}
	
	/**
	 * Gets the table name (always returns "event")
	 * 
	 * @param boolean $read changes the table name if a database view is provided for reading, rather than a table
	 * 
	 * @return string
	 */
	public static function getTable($read=true) {
		return "event";
	}
	
	/**
	 * Gets the primary key
	 * 
	 * @return array
	 */
	public static function getPrimaryKey() {
		return array("id");
	}
	
	/**
	 * Gets the field the key references
	 * 
	 * @return array
	 */
	public static function getForeignKeys() {
		$keys = array();

		$std = new \stdClass();
		$std->table = "venue";
		$std->field = "id";
		
		$keys['venue'] = $std;	
		$std = new \stdClass();
		$std->table = "event";
		$std->field = "id";
		
		$keys['parent'] = $std;	
		return $keys;
	}
		
	/**
	 * Gets all Venue associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getVenue() {
		return \Model\Venue::Fetch($this->venue);
	}			
		
	/**
	 * Gets all objects relating to Venue
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByVenue(Venue $class) {
		$c = get_called_class();
		return $c::getByAttribute("venue", $class->id);
	}
		
	/**
	 * Gets all Event associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getParent() {
		return \Model\Event::Fetch($this->parent);
	}			
		
	/**
	 * Gets all objects relating to Event
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByParent(Event $class) {
		$c = get_called_class();
		return $c::getByAttribute("parent", $class->id);
	}

	/**
	 * Gets all Events relating to this model by the field parent
	 * 
	 * @return array
	 */	
	public function getEvents() {
		return \Model\Event::getByParent($this);
	}
			
		
	public function getBy() {
		return self::getByAttributes(array());
	}
	
	public function bubbleUpdateResult($update_result, $loop_control=array()) {
		if (in_array(get_class(), $loop_control)) {
			return;
		}
		$loop_control[] = get_class();
		$update_result->module = get_class();
		$c = get_class();
		$update_result->module_table = $c::getTable();
		if (\System\Library\StdLib::parent_method_exists($this, "bubbleUpdateResult", __CLASS__)) {
			parent::bubbleUpdateResult($update_result, $loop_control);	
		}
		\Library\RTCQueue::Send("/model/".self::getTable()."/{$this->id}", $update_result);
		return;
		$obj = $this->getVenue();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}

		$obj = $this->getParent();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}
	}
}