<?php
/**
 * Autogenerated model for \Model\Thread
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace System\Model;
	
/**
 * Autogenerated model for \Model\Thread
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Thread extends \Model\DBObject {
	
	/**
	* int(11)
	* 
	* @var int $id 
	*/
	public $id;
	
	/**
	* varchar(255)
	* 
	* @var string $name 
	*/
	public $name;
	
	/**
	* int(11)
	* 
	* @var int $parent 
	*/
	public $parent;
	
	/**
	* varchar(255)
	* 
	* @var string $description 
	*/
	public $description;
	
	/**
	* varchar(255)
	* 
	* @var string $source_table 
	*/
	public $source_table;
	
	/**
	* int(11)
	* 
	* @var int $source_id 
	*/
	public $source_id;	
	/**
	 * Lists all the columns in the database
	 *
	 * @return array
	 */
	public static function getDBColumns() {
		return array("id","name","parent","description","source_table","source_id");
	}
	
	/**
	 * Gets the table name (always returns "thread")
	 * 
	 * @param boolean $read changes the table name if a database view is provided for reading, rather than a table
	 * 
	 * @return string
	 */
	public static function getTable($read=true) {
		return "thread";
	}
	
	/**
	 * Gets the primary key
	 * 
	 * @return array
	 */
	public static function getPrimaryKey() {
		return array("id");
	}
	
	/**
	 * Gets the field the key references
	 * 
	 * @return array
	 */
	public static function getForeignKeys() {
		$keys = array();

		$std = new \stdClass();
		$std->table = "thread";
		$std->field = "id";
		
		$keys['parent'] = $std;	
		return $keys;
	}
		
	/**
	 * Gets all Thread associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getParent() {
		return \Model\Thread::Fetch($this->parent);
	}			
		
	/**
	 * Gets all objects relating to Thread
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByParent(Thread $class) {
		$c = get_called_class();
		return $c::getByAttribute("parent", $class->id);
	}

	/**
	 * Gets all Tasks relating to this model by the field thread
	 * 
	 * @return array
	 */	
	public function getTasks() {
		return \Model\Task::getByThread($this);
	}
	

	/**
	 * Gets all Threads relating to this model by the field parent
	 * 
	 * @return array
	 */	
	public function getThreads() {
		return \Model\Thread::getByParent($this);
	}
	

	/**
	 * Gets all ThreadPosts relating to this model by the field thread
	 * 
	 * @return array
	 */	
	public function getThreadPosts() {
		return \Model\ThreadPost::getByThread($this);
	}
	
	public function bubbleUpdateResult($update_result, $loop_control=array()) {
		if (in_array(get_class(), $loop_control)) {
			return;
		}
		$loop_control[] = get_class();
		$update_result->module = get_class();
		$c = get_class();
		$update_result->module_table = $c::getTable();
		if (\System\Library\StdLib::parent_method_exists($this, "bubbleUpdateResult", __CLASS__)) {
			parent::bubbleUpdateResult($update_result, $loop_control);	
		}
		\Library\RTCQueue::Send("/model/".self::getTable()."/{$this->id}", $update_result);
		return;
		$obj = $this->getParent();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}
	}
}