<?php
/**
 * Autogenerated model for \Model\VenueCheck
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://www.mercianlabels.com
 *
 */
namespace System\Model;
	
/**
 * Autogenerated model for \Model\VenueCheck
 * 
 * PHP version 5.4
 *
 * @category Model
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  GNU v3.0 http://www.gnu.org/licenses/gpl-3.0.txt
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class VenueCheck extends \Model\DBObject {
	
	/**
	* int(11)
	* 
	* @var int $id 
	*/
	public $id;
	
	/**
	* int(11)
	* 
	* @var int $venue 
	*/
	public $venue;
	
	/**
	* int(11)
	* 
	* @var int $time_checkout 
	*/
	public $time_checkout;
	
	/**
	* int(11)
	* 
	* @var int $time_expires 
	*/
	public $time_expires;
	
	/**
	* int(11)
	* 
	* @var int $time_completed 
	*/
	public $time_completed;
	
	/**
	* int(11)
	* 
	* @var int $time_checkin 
	*/
	public $time_checkin;
	
	/**
	* int(11)
	* 
	* @var int $actor 
	*/
	public $actor;
	
	/**
	* int(11)
	* 
	* @var int $status 
	*/
	public $status;	
	/**
	 * Lists all the columns in the database
	 *
	 * @return array
	 */
	public static function getDBColumns() {
		return array("id","venue","time_checkout","time_expires","time_completed","time_checkin","actor","status");
	}
	
	/**
	 * Gets the table name (always returns "venue_check")
	 * 
	 * @param boolean $read changes the table name if a database view is provided for reading, rather than a table
	 * 
	 * @return string
	 */
	public static function getTable($read=true) {
		return "venue_check";
	}
	
	/**
	 * Gets the primary key
	 * 
	 * @return array
	 */
	public static function getPrimaryKey() {
		return array("id");
	}
	
	/**
	 * Gets the field the key references
	 * 
	 * @return array
	 */
	public static function getForeignKeys() {
		$keys = array();

		$std = new \stdClass();
		$std->table = "venue";
		$std->field = "id";
		
		$keys[venue] = $std;	
		$std = new \stdClass();
		$std->table = "person";
		$std->field = "id";
		
		$keys[actor] = $std;	
		return $keys;
	}
		
	/**
	 * Gets all Venue associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getVenue() {
		return \Model\Venue::Fetch($this->venue);
	}			
		
	/**
	 * Gets all objects relating to Venue
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByVenue(Venue $class) {
		$c = get_called_class();
		return $c::getByAttribute("venue", $class->id);
	}
		
	/**
	 * Gets all Person associated with this object
	 * 
	 * @return System\Model$className
	 */
	public function getActor() {
		return \Model\Person::Fetch($this->actor);
	}			
		
	/**
	 * Gets all objects relating to Person
	 * 
	 * @param $class \Model$className Get objects relating to this class
	 * 
	 * @return array
	 */		
	public static function getByActor(Person $class) {
		$c = get_called_class();
		return $c::getByAttribute("actor", $class->id);
	}

	/**
	 * Gets all VenueCheckResponses relating to this model by the field venue_check
	 * 
	 * @return array
	 */	
	public function getVenueCheckResponses() {
		return \Model\VenueCheckResponse::getByVenueCheck($this);
	}
			
		
	public function getBy() {
		return self::getByAttributes(array());
	}
	
	public function bubbleUpdateResult($update_result, $loop_control=array()) {
		if (in_array(get_class(), $loop_control)) {
			return;
		}
		$loop_control[] = get_class();
		$update_result->module = get_class();
		$c = get_class();
		$update_result->module_table = $c::getTable();
		if (\System\Library\StdLib::parent_method_exists($this, "bubbleUpdateResult", __CLASS__)) {
			parent::bubbleUpdateResult($update_result, $loop_control);	
		}
		\Library\RTCQueue::Send("/model/".self::getTable()."/{$this->id}", $update_result);
		return;
		$obj = $this->getVenue();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}

		$obj = $this->getActor();
		if ($obj) {
			$obj->bubbleUpdateResult($update_result, $loop_control);
		}
	}
}