<?php
/**
 * API Generation for the framework
 * 
 * PHP version 5.4
 * 
 * @category  API
 * @package   Boiler
 * @author    Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @copyright 2013 Mercian Labels
 * @license   http://www.mercianlabels.com All Rights Reserved
 * @link      http://www.mercianlabels.com
 */
namespace Controller\Api;

/**
 * Autogenerated stub for API access to the model \Model\Person
 * 
 * PHP version 5.4
 *
 * @category API
 * @package  Boiler
 * @author   ivebeenlinuxed <will.tinsdeall@mercianlabels.com>
 * @license  All Rights Reserved
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Person extends \System\Controller\Api\Person {
	public function Search() {
		echo json_encode(array("data"=>\Model\Person::Search(array("first_name", "last_name"), $_GET['q'], null, true)));
	}
}