<?php
/**
 * API Generation for the framework
 * 
 * PHP version 5.4
 * 
 * @category  API
 * @package   Boiler
 * @author    Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @copyright 2013 Mercian Labels
 * @license   http://www.mercianlabels.com All Rights Reserved
 * @link      http://www.mercianlabels.com
 */
namespace Controller\Api;

/**
 * Autogenerated stub for API access to the model \Model\Venue_Check
 * 
 * PHP version 5.4
 *
 * @category API
 * @package  Boiler
 * @author   ivebeenlinuxed <will.tinsdeall@mercianlabels.com>
 * @license  All Rights Reserved
 * @version  GIT: $Id$
 * @link     http://www.mercianlabels.com
 *
 */
class Venue_Check extends \System\Controller\Api\Venue_Check {
}